title: Stack Problems
description: My Personal Stack Problems
author: David Zambrano
github: https://github.com/davazamb
about: I am freelance I.T-Software developer; C#/.Net MVC-Core, Xamarin.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/zambrano.david"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/davazamb"
    - icon: fa-linkedin
      link: "https://ve.linkedin.com/in/david-zambrano"
    - icon: fa-youtube
      link: "youtube.com/c/DavidZambrano10"
    - icon: fa-google-plus-squaree
      link: "google.com/+DavidZambrano10"

share:
  twitter_username: davazamb
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/davazamb
    - text: XML Feed
      url: /feed.xml

url: "https://davazamb.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
